// GENERATED CODE - DO NOT MODIFY BY HAND.
// Üretim: tools/importers/turhanlar_to_demo_catalog.py

import '../models/category.dart';
import '../models/product.dart';
import '../models/product_media.dart';

const _catDokumSobalar = Category(
  id: 'cat_dokum-sobalar',
  name: 'Döküm Sobalar',
  slug: 'dokum-sobalar',
  sortOrder: 1,
  isActive: true,
);

const _catSacSobalar = Category(
  id: 'cat_sac-sobalar',
  name: 'Sac Sobalar',
  slug: 'sac-sobalar',
  sortOrder: 2,
  isActive: true,
);

const List<Category> demoCategories = <Category>[
  _catDokumSobalar,
  _catSacSobalar,
];

const List<Product> demoProducts = <Product>[
  Product(
    id: 'prd_caldera-pelet-ve-odun-sominesi',
    categoryId: 'cat_dokum-sobalar',
    name: 'Caldera PELET ve Odun Şöminesi',
    slug: 'caldera-pelet-ve-odun-sominesi',
    longDesc: '**Genel Ölçüler:**\n\n- Yükseklik: 82 cm\n\n- Genişlik: 45 cm\n\n- En: 31 cm\n\n**Fırın Ölçüleri:**\n\n- Yükseklik: 34 cm\n\n- Genişlik: 17 cm\n\n- Derinlik: 28 cm',
    dimensions: ProductDimensions(w: 45, h: 82, d: 28),
    isFeatured: true,
    isPublished: true,
  ),
  Product(
    id: 'prd_milan-kuzineli-somine',
    categoryId: 'cat_dokum-sobalar',
    name: 'Milan Kuzineli Şömine',
    slug: 'milan-kuzineli-somine',
    longDesc: '**Genel Ölçüler:**\n\n- Yükseklik: 82 cm\n\n- Genişlik: 45 cm\n\n- En: 31 cm\n\n**Fırın Ölçüleri:**\n\n- Yükseklik: 34 cm\n\n- Genişlik: 17 cm\n\n- Derinlik: 28 cm',
    dimensions: ProductDimensions(w: 45, h: 82, d: 28),
    isFeatured: true,
    isPublished: true,
  ),
  Product(
    id: 'prd_oscar-firinsiz-somine',
    categoryId: 'cat_dokum-sobalar',
    name: 'Oscar Fırınsız Şömine',
    slug: 'oscar-firinsiz-somine',
    longDesc: '**Genel Ölçüler:**\n\n- Yükseklik: 82 cm\n\n- Genişlik: 45 cm\n\n- En: 31 cm\n\n**Fırın Ölçüleri:**\n\n- Yükseklik: 34 cm\n\n- Genişlik: 17 cm\n\n- Derinlik: 28 cm',
    dimensions: ProductDimensions(w: 45, h: 82, d: 28),
    isFeatured: true,
    isPublished: true,
  ),
  Product(
    id: 'prd_paris-firinli-somine',
    categoryId: 'cat_dokum-sobalar',
    name: 'Paris Fırınlı Şömine',
    slug: 'paris-firinli-somine',
    longDesc: '**Genel Ölçüler:**\n\n- Yükseklik: 95 cm\n\n- Genişlik: 45.5 cm\n\n- En: 41.5 cm\n\n**Fırın Ölçüleri:**\n\n- Yükseklik: 17 cm\n\n- Genişlik: 26 cm\n\n- Derinlik: 34 cm\n\n**Yanma Haznesi Ölçüleri:**\n\n- Genişlik: 39 cm\n\n- En: 33 cm\n\n- Yükseklik: 45 cm',
    dimensions: ProductDimensions(w: 45.5, h: 95, d: 34),
    isFeatured: true,
    isPublished: true,
  ),
  Product(
    id: 'prd_tam-dokum-firinli-somine',
    categoryId: 'cat_dokum-sobalar',
    name: 'Tam Döküm Fırınlı Şömine',
    slug: 'tam-dokum-firinli-somine',
    longDesc: '**Genel Ölçüler:**\n\n- Yükseklik: 82 cm\n\n- Genişlik: 45 cm\n\n- En: 31 cm\n\n**Fırın Ölçüleri:**\n\n- Yükseklik: 34 cm\n\n- Genişlik: 17 cm\n\n- Derinlik: 28 cm',
    dimensions: ProductDimensions(w: 45, h: 82, d: 28),
    isFeatured: true,
    isPublished: true,
  ),
  Product(
    id: 'prd_tam-dokum-firinsiz-somine',
    categoryId: 'cat_dokum-sobalar',
    name: 'Tam Döküm Fırınsız Şömine',
    slug: 'tam-dokum-firinsiz-somine',
    longDesc: '**Genel Ölçüler:**\n\n- Yükseklik: 82 cm\n\n- Genişlik: 45 cm\n\n- En: 31 cm\n\n**Fırın Ölçüleri:**\n\n- Yükseklik: 34 cm\n\n- Genişlik: 17 cm\n\n- Derinlik: 28 cm',
    dimensions: ProductDimensions(w: 45, h: 82, d: 28),
    isFeatured: true,
    isPublished: true,
  ),
  Product(
    id: 'prd_vesta-pelet-ve-odun-sominesi',
    categoryId: 'cat_dokum-sobalar',
    name: 'Vesta PELET ve odun şöminesi',
    slug: 'vesta-pelet-ve-odun-sominesi',
    longDesc: '**Genel Ölçüler:**\n\n- Yükseklik: 82 cm\n\n- Genişlik: 45 cm\n\n- En: 31 cm\n\n**Fırın Ölçüleri:**\n\n- Yükseklik: 34 cm\n\n- Genişlik: 17 cm\n\n- Derinlik: 28 cm',
    dimensions: ProductDimensions(w: 45, h: 82, d: 28),
    isFeatured: false,
    isPublished: true,
  ),
  Product(
    id: 'prd_zumrut-pelet-ve-odun-sominesi',
    categoryId: 'cat_dokum-sobalar',
    name: 'Zümrüt PELET ve Odun Şöminesi',
    slug: 'zumrut-pelet-ve-odun-sominesi',
    longDesc: '**Genel Ölçüler:**\n\n- Yükseklik: 82 cm\n\n- Genişlik: 45 cm\n\n- En: 31 cm\n\n**Fırın Ölçüleri:**\n\n- Yükseklik: 34 cm\n\n- Genişlik: 17 cm\n\n- Derinlik: 28 cm',
    dimensions: ProductDimensions(w: 45, h: 82, d: 28),
    isFeatured: false,
    isPublished: true,
  ),
  Product(
    id: 'prd_ekonomik-dokum-kuzine-camli',
    categoryId: 'cat_sac-sobalar',
    name: 'Ekonomik döküm kuzine Camlı',
    slug: 'ekonomik-dokum-kuzine-camli',
    longDesc: '**Ürün Bilgileri:**\n\n- Camlı ve camsız model seçeneği\n\n- Kahverengi ve mat EMAYE boya\n\n- Yükseklik: 60 cm\n\n- Genişlik: 80 cm\n\n- En: 43 cm\n\n- Fırın içi: 20x40x40 cm\n\n- Baca çapı: 13 cm\n\n- Yakıt cinsi: Katı yakıt\n\n- Isı gücü: 8 kW',
    dimensions: ProductDimensions(w: 80, h: 60, d: 43),
    isFeatured: false,
    isPublished: true,
  ),
  Product(
    id: 'prd_ekonomik-kovali-kuzine',
    categoryId: 'cat_sac-sobalar',
    name: 'Ekonomik Kovalı kuzine',
    slug: 'ekonomik-kovali-kuzine',
    longDesc: '**Teknik Özellikler:**\n\n- Yükseklik: 60 cm\n\n- Genişlik: 80 cm\n\n- En: 43 cm\n\n- Isı Gücü: 7 kW\n\n- Baca Çapı: 13 cm\n\n- Yakıt Cinsi: Katı Yakıt\n\n**Fırın İçi Ölçüleri:**\n\n- Yükseklik: 20 cm\n\n- Genişlik: 40 cm\n\n- Derinlik: 40 cm',
    dimensions: ProductDimensions(w: 80, h: 60, d: 40),
    isFeatured: false,
    isPublished: true,
  ),
  Product(
    id: 'prd_ekonomik-lux-dokum-kuzine',
    categoryId: 'cat_sac-sobalar',
    name: 'Ekonomik LÜX döküm kuzine',
    slug: 'ekonomik-lux-dokum-kuzine',
    longDesc: '**Ürün Özellikleri:**\n\n- Camlı ve camsız model seçeneği\n\n- Kahverengi ve mat EMAYE boya\n\n- Yükseklik: 60 cm\n\n- Genişlik: 80 cm\n\n- En: 43 cm\n\n- Fırın içi: 20x40x40 cm\n\n- Baca çapı: 13 cm\n\n- Yakıt cinsi: Katı yakıt\n\n- Isı gücü: 8 kW',
    dimensions: ProductDimensions(w: 80, h: 60, d: 43),
    isFeatured: false,
    isPublished: true,
  ),
  Product(
    id: 'prd_ekonomik-sac-kuzine-camsiz',
    categoryId: 'cat_sac-sobalar',
    name: 'Ekonomik Sac Kuzine Camsız',
    slug: 'ekonomik-sac-kuzine-camsiz',
    longDesc: '**Teknik Özellikler:**\n\n- Yükseklik: 60 cm\n\n- Genişlik: 80 cm\n\n- En: 43 cm\n\n- Fırın: 20 x 40 x 40 cm\n\n- Baca Çapı: 13 cm\n\n- Yakıt Cinsi: Katı Yakıtlı',
    dimensions: ProductDimensions(w: 80, h: 60, d: 43),
    isFeatured: false,
    isPublished: true,
  ),
];

const List<ProductMedia> demoMedia = <ProductMedia>[
  ProductMedia(
    id: 'med_caldera-pelet-ve-odun-sominesi_img_1',
    productId: 'prd_caldera-pelet-ve-odun-sominesi',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/caldera-pelet-ve-odun-sominesi_caldera1.jpg',
    altText: 'Caldera PELET ve Odun Şöminesi',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_caldera-pelet-ve-odun-sominesi_img_2',
    productId: 'prd_caldera-pelet-ve-odun-sominesi',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/caldera-pelet-ve-odun-sominesi_caldera2.jpg',
    altText: 'Caldera PELET ve Odun Şöminesi',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_caldera-pelet-ve-odun-sominesi_img_3',
    productId: 'prd_caldera-pelet-ve-odun-sominesi',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/caldera-pelet-ve-odun-sominesi_caldera3.jpg',
    altText: 'Caldera PELET ve Odun Şöminesi',
    sortOrder: 2,
  ),
  ProductMedia(
    id: 'med_milan-kuzineli-somine_img_1',
    productId: 'prd_milan-kuzineli-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/milan-kuzineli-somine_milan1.jpg',
    altText: 'Milan Kuzineli Şömine',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_milan-kuzineli-somine_img_2',
    productId: 'prd_milan-kuzineli-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/milan-kuzineli-somine_milan2.jpg',
    altText: 'Milan Kuzineli Şömine',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_milan-kuzineli-somine_img_3',
    productId: 'prd_milan-kuzineli-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/milan-kuzineli-somine_milan3.jpg',
    altText: 'Milan Kuzineli Şömine',
    sortOrder: 2,
  ),
  ProductMedia(
    id: 'med_oscar-firinsiz-somine_img_1',
    productId: 'prd_oscar-firinsiz-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/oscar-firinsiz-somine_oscar1.jpg',
    altText: 'Oscar Fırınsız Şömine',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_oscar-firinsiz-somine_img_2',
    productId: 'prd_oscar-firinsiz-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/oscar-firinsiz-somine_oscar2.jpg',
    altText: 'Oscar Fırınsız Şömine',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_oscar-firinsiz-somine_img_3',
    productId: 'prd_oscar-firinsiz-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/oscar-firinsiz-somine_oscar3.jpg',
    altText: 'Oscar Fırınsız Şömine',
    sortOrder: 2,
  ),
  ProductMedia(
    id: 'med_paris-firinli-somine_img_1',
    productId: 'prd_paris-firinli-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/paris-firinli-somine_paris1.jpg',
    altText: 'Paris Fırınlı Şömine',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_paris-firinli-somine_img_2',
    productId: 'prd_paris-firinli-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/paris-firinli-somine_paris2.jpg',
    altText: 'Paris Fırınlı Şömine',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_paris-firinli-somine_img_3',
    productId: 'prd_paris-firinli-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/paris-firinli-somine_paris3.jpg',
    altText: 'Paris Fırınlı Şömine',
    sortOrder: 2,
  ),
  ProductMedia(
    id: 'med_tam-dokum-firinli-somine_img_1',
    productId: 'prd_tam-dokum-firinli-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/tam-dokum-firinli-somine_tam1.jpg',
    altText: 'Tam Döküm Fırınlı Şömine',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_tam-dokum-firinli-somine_img_2',
    productId: 'prd_tam-dokum-firinli-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/tam-dokum-firinli-somine_tam2.jpg',
    altText: 'Tam Döküm Fırınlı Şömine',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_tam-dokum-firinli-somine_img_3',
    productId: 'prd_tam-dokum-firinli-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/tam-dokum-firinli-somine_tam3.jpg',
    altText: 'Tam Döküm Fırınlı Şömine',
    sortOrder: 2,
  ),
  ProductMedia(
    id: 'med_tam-dokum-firinsiz-somine_img_1',
    productId: 'prd_tam-dokum-firinsiz-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/tam-dokum-firinsiz-somine_tam01.jpg',
    altText: 'Tam Döküm Fırınsız Şömine',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_tam-dokum-firinsiz-somine_img_2',
    productId: 'prd_tam-dokum-firinsiz-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/tam-dokum-firinsiz-somine_tam02.jpg',
    altText: 'Tam Döküm Fırınsız Şömine',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_tam-dokum-firinsiz-somine_img_3',
    productId: 'prd_tam-dokum-firinsiz-somine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/tam-dokum-firinsiz-somine_tam03.jpg',
    altText: 'Tam Döküm Fırınsız Şömine',
    sortOrder: 2,
  ),
  ProductMedia(
    id: 'med_vesta-pelet-ve-odun-sominesi_img_1',
    productId: 'prd_vesta-pelet-ve-odun-sominesi',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/vesta-pelet-ve-odun-sominesi_vesta1.jpg',
    altText: 'Vesta PELET ve odun şöminesi',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_vesta-pelet-ve-odun-sominesi_img_2',
    productId: 'prd_vesta-pelet-ve-odun-sominesi',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/vesta-pelet-ve-odun-sominesi_vesta2.jpg',
    altText: 'Vesta PELET ve odun şöminesi',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_vesta-pelet-ve-odun-sominesi_img_3',
    productId: 'prd_vesta-pelet-ve-odun-sominesi',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/vesta-pelet-ve-odun-sominesi_vesta3.jpg',
    altText: 'Vesta PELET ve odun şöminesi',
    sortOrder: 2,
  ),
  ProductMedia(
    id: 'med_zumrut-pelet-ve-odun-sominesi_img_1',
    productId: 'prd_zumrut-pelet-ve-odun-sominesi',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/zumrut-pelet-ve-odun-sominesi_zumrut1.jpg',
    altText: 'Zümrüt PELET ve Odun Şöminesi',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_zumrut-pelet-ve-odun-sominesi_img_2',
    productId: 'prd_zumrut-pelet-ve-odun-sominesi',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/zumrut-pelet-ve-odun-sominesi_zumrut2.jpg',
    altText: 'Zümrüt PELET ve Odun Şöminesi',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_zumrut-pelet-ve-odun-sominesi_img_3',
    productId: 'prd_zumrut-pelet-ve-odun-sominesi',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/zumrut-pelet-ve-odun-sominesi_zumrut3.jpg',
    altText: 'Zümrüt PELET ve Odun Şöminesi',
    sortOrder: 2,
  ),
  ProductMedia(
    id: 'med_ekonomik-dokum-kuzine-camli_img_1',
    productId: 'prd_ekonomik-dokum-kuzine-camli',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-dokum-kuzine-camli_sacsoba01.jpg',
    altText: 'Ekonomik döküm kuzine Camlı',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_ekonomik-dokum-kuzine-camli_img_2',
    productId: 'prd_ekonomik-dokum-kuzine-camli',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-dokum-kuzine-camli_sacsoba02.jpg',
    altText: 'Ekonomik döküm kuzine Camlı',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_ekonomik-dokum-kuzine-camli_img_3',
    productId: 'prd_ekonomik-dokum-kuzine-camli',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-dokum-kuzine-camli_sacsoba03.jpg',
    altText: 'Ekonomik döküm kuzine Camlı',
    sortOrder: 2,
  ),
  ProductMedia(
    id: 'med_ekonomik-kovali-kuzine_img_1',
    productId: 'prd_ekonomik-kovali-kuzine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-kovali-kuzine_sacsoba0001.jpg',
    altText: 'Ekonomik Kovalı kuzine',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_ekonomik-kovali-kuzine_img_2',
    productId: 'prd_ekonomik-kovali-kuzine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-kovali-kuzine_sacsoba0002.jpg',
    altText: 'Ekonomik Kovalı kuzine',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_ekonomik-kovali-kuzine_img_3',
    productId: 'prd_ekonomik-kovali-kuzine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-kovali-kuzine_sacsoba0003.jpg',
    altText: 'Ekonomik Kovalı kuzine',
    sortOrder: 2,
  ),
  ProductMedia(
    id: 'med_ekonomik-lux-dokum-kuzine_img_1',
    productId: 'prd_ekonomik-lux-dokum-kuzine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-lux-dokum-kuzine_sacsoba01.jpg',
    altText: 'Ekonomik LÜX döküm kuzine',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_ekonomik-lux-dokum-kuzine_img_2',
    productId: 'prd_ekonomik-lux-dokum-kuzine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-lux-dokum-kuzine_sacsoba02.jpg',
    altText: 'Ekonomik LÜX döküm kuzine',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_ekonomik-lux-dokum-kuzine_img_3',
    productId: 'prd_ekonomik-lux-dokum-kuzine',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-lux-dokum-kuzine_sacsoba03.jpg',
    altText: 'Ekonomik LÜX döküm kuzine',
    sortOrder: 2,
  ),
  ProductMedia(
    id: 'med_ekonomik-sac-kuzine-camsiz_img_1',
    productId: 'prd_ekonomik-sac-kuzine-camsiz',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-sac-kuzine-camsiz_sacsoba001.jpg',
    altText: 'Ekonomik Sac Kuzine Camsız',
    sortOrder: 0,
  ),
  ProductMedia(
    id: 'med_ekonomik-sac-kuzine-camsiz_img_2',
    productId: 'prd_ekonomik-sac-kuzine-camsiz',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-sac-kuzine-camsiz_sacsoba002.jpg',
    altText: 'Ekonomik Sac Kuzine Camsız',
    sortOrder: 1,
  ),
  ProductMedia(
    id: 'med_ekonomik-sac-kuzine-camsiz_img_3',
    productId: 'prd_ekonomik-sac-kuzine-camsiz',
    kind: ProductMediaKind.image,
    url: '/imported/turhanlar/ekonomik-sac-kuzine-camsiz_sacsoba003.jpg',
    altText: 'Ekonomik Sac Kuzine Camsız',
    sortOrder: 2,
  ),
];
